//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neon.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neon.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} and {1} do not match.&quot;.
        /// </summary>
        public static string Error_Validation_Compare {
            get {
                return ResourceManager.GetString("Error_Validation_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        public static string Error_Validation_Invalid {
            get {
                return ResourceManager.GetString("Error_Validation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Error_Validation_Required {
            get {
                return ResourceManager.GetString("Error_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have a length up to {1}.
        /// </summary>
        public static string Error_Validation_StringLength {
            get {
                return ResourceManager.GetString("Error_Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have a length between {2} and {1}..
        /// </summary>
        public static string Error_Validation_StringLengthWithMin {
            get {
                return ResourceManager.GetString("Error_Validation_StringLengthWithMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred..
        /// </summary>
        public static string Error_Validation_UnexpectedError {
            get {
                return ResourceManager.GetString("Error_Validation_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters, digits, dashes and underscores..
        /// </summary>
        public static string Error_Validation_UsernameInvalidCharacters {
            get {
                return ResourceManager.GetString("Error_Validation_UsernameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not found..
        /// </summary>
        public static string Error_Validation_UsernameNotFound {
            get {
                return ResourceManager.GetString("Error_Validation_UsernameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is taken..
        /// </summary>
        public static string Error_Validation_UsernameTaken {
            get {
                return ResourceManager.GetString("Error_Validation_UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password..
        /// </summary>
        public static string Error_Validation_WrongPassword {
            get {
                return ResourceManager.GetString("Error_Validation_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Layout_Nav_Guest {
            get {
                return ResourceManager.GetString("Layout_Nav_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Layout_Nav_Login {
            get {
                return ResourceManager.GetString("Layout_Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Nav_Logout {
            get {
                return ResourceManager.GetString("Layout_Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neon.
        /// </summary>
        public static string Layout_Nav_Neon {
            get {
                return ResourceManager.GetString("Layout_Nav_Neon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Layout_Nav_Register {
            get {
                return ResourceManager.GetString("Layout_Nav_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already active.
        /// </summary>
        public static string Layout_Title_AlreadyActive {
            get {
                return ResourceManager.GetString("Layout_Title_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay.
        /// </summary>
        public static string Layout_Title_Gameplay {
            get {
                return ResourceManager.GetString("Layout_Title_Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Layout_Title_Guest {
            get {
                return ResourceManager.GetString("Layout_Title_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Layout_Title_Login {
            get {
                return ResourceManager.GetString("Layout_Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Layout_Title_Register {
            get {
                return ResourceManager.GetString("Layout_Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string User_Button_Play {
            get {
                return ResourceManager.GetString("User_Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string User_Property_Password {
            get {
                return ResourceManager.GetString("User_Property_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string User_Property_RememberMe {
            get {
                return ResourceManager.GetString("User_Property_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string User_Property_RepeatPassword {
            get {
                return ResourceManager.GetString("User_Property_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string User_Property_Username {
            get {
                return ResourceManager.GetString("User_Property_Username", resourceCulture);
            }
        }
    }
}
